### PR TITLE
Issue38

### LINKED ISSUE #38: Wrong API key not throwing errors
Tried to run the example from readme with a wrong API key, and got a success message.
It seems that 401 errors (maybe other 4XX?) are not handled as errors in the lib.

### PR DESCRIPTION
**Pull request by beardyman**
closes #38

### CODE REVIEW

File: lib/SparkPost/APIResource.php [hunk 1]
```diff
@@ -186,24 +188,29 @@ private function callResource( $action, $resourcePath=null, $options=[] ) {
...
-        throw new \Exception('The specified resource does not exist', 404);
+
+      // Handle 4XX responses, 5XX responses will throw an HttpAdapterException
+      if ($statusCode < 400) {
+        return json_decode($response->getBody()->getContents(), true);
+      } else {
+        if ($statusCode === 404) {
+          throw new APIResponseException('The specified resource does not exist', 404);
+        }
+        throw new APIResponseException('Received bad response from '.ucfirst($this->endpoint).' API: '. $statusCode );
```
Comment (richleland) [inline lib/SparkPost/APIResource.php]: add spaces around concat operators

File: lib/SparkPost/APIResource.php [hunk 2]
```diff
@@ -186,24 +188,29 @@ private function callResource( $action, $resourcePath=null, $options=[] ) {
...
-     * Handles 5XX Errors, Configuration Errors, and a catch all for other errors
+     * Configuration Errors, and a catch all for other errors
      */
     catch (\Exception $exception) {
-      throw new \Exception('Unable to contact '.ucfirst($this->endpoint).' API: '. $exception->getMessage());
+      if($exception instanceof APIResponseException) {
+        throw $exception;
+      }
+
+      throw new APIResponseException('Unable to contact '.ucfirst($this->endpoint).' API: '. $exception->getMessage());
```
Comment (richleland) [inline lib/SparkPost/APIResource.php]: add spaces around concat operators
